events {}

http {

  server {
    listen 80;
    server_name localhost;

    # 정적 파일
    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri /index.html;
    }

    # backend API
    location /api/ {
      proxy_pass http://backend:8081/;
    }

    # llm
    location /llm/ {
      proxy_pass http://llm:8000/;
    }
  }
}
    